services:
    _defaults:
        autoconfigure: true
    Contao\SwbGasRegForm\Controller\FrontendModule\SgrfEditFormController:
        tags: {}
    Contao\SwbGasRegForm\Controller\TokenController:
        arguments:
            - '@contao.security.token_checker'
