services:
    _defaults:
        autoconfigure: true
    Contao\SwbGasRegForm\Controller\SgrfConnectorController:
        arguments:
            - '@contao.framework'
            - '@feopenidprovider.resourceservice'
        calls:
            - method: setContainer
              arguments: ['@service_container']
